# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = D:/Mine/CMake/bin/cmake.exe

# The command to remove a file.
RM = D:/Mine/CMake/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:/Mine/stm32_pm2025

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:/Mine/stm32_pm2025/cmake-build-debug-mingw

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	D:/Mine/CMake/bin/cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	D:/Mine/CMake/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:/Mine/stm32_pm2025/cmake-build-debug-mingw/CMakeFiles D:/Mine/stm32_pm2025/cmake-build-debug-mingw//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:/Mine/stm32_pm2025/cmake-build-debug-mingw/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stm32_timer_blink.elf

# Build rule for target.
stm32_timer_blink.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stm32_timer_blink.elf
.PHONY : stm32_timer_blink.elf

# fast build rule for target.
stm32_timer_blink.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/build
.PHONY : stm32_timer_blink.elf/fast

#=============================================================================
# Target rules for targets named bin

# Build rule for target.
bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bin
.PHONY : bin

# fast build rule for target.
bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bin.dir/build.make CMakeFiles/bin.dir/build
.PHONY : bin/fast

#=============================================================================
# Target rules for targets named hex

# Build rule for target.
hex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hex
.PHONY : hex

# fast build rule for target.
hex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/build
.PHONY : hex/fast

#=============================================================================
# Target rules for targets named size

# Build rule for target.
size: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 size
.PHONY : size

# fast build rule for target.
size/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/size.dir/build.make CMakeFiles/size.dir/build
.PHONY : size/fast

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash.dir/build.make CMakeFiles/flash.dir/build
.PHONY : flash/fast

main.obj: main.c.obj
.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/main.c.s
.PHONY : main.c.s

stm32/startup/startup_stm32f10x_md.obj: stm32/startup/startup_stm32f10x_md.c.obj
.PHONY : stm32/startup/startup_stm32f10x_md.obj

# target to build an object file
stm32/startup/startup_stm32f10x_md.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/stm32/startup/startup_stm32f10x_md.c.obj
.PHONY : stm32/startup/startup_stm32f10x_md.c.obj

stm32/startup/startup_stm32f10x_md.i: stm32/startup/startup_stm32f10x_md.c.i
.PHONY : stm32/startup/startup_stm32f10x_md.i

# target to preprocess a source file
stm32/startup/startup_stm32f10x_md.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/stm32/startup/startup_stm32f10x_md.c.i
.PHONY : stm32/startup/startup_stm32f10x_md.c.i

stm32/startup/startup_stm32f10x_md.s: stm32/startup/startup_stm32f10x_md.c.s
.PHONY : stm32/startup/startup_stm32f10x_md.s

# target to generate assembly for a file
stm32/startup/startup_stm32f10x_md.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/stm32/startup/startup_stm32f10x_md.c.s
.PHONY : stm32/startup/startup_stm32f10x_md.c.s

stm32/system_stm32f10x.obj: stm32/system_stm32f10x.c.obj
.PHONY : stm32/system_stm32f10x.obj

# target to build an object file
stm32/system_stm32f10x.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/stm32/system_stm32f10x.c.obj
.PHONY : stm32/system_stm32f10x.c.obj

stm32/system_stm32f10x.i: stm32/system_stm32f10x.c.i
.PHONY : stm32/system_stm32f10x.i

# target to preprocess a source file
stm32/system_stm32f10x.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/stm32/system_stm32f10x.c.i
.PHONY : stm32/system_stm32f10x.c.i

stm32/system_stm32f10x.s: stm32/system_stm32f10x.c.s
.PHONY : stm32/system_stm32f10x.s

# target to generate assembly for a file
stm32/system_stm32f10x.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/stm32/system_stm32f10x.c.s
.PHONY : stm32/system_stm32f10x.c.s

syscalls/syscalls.obj: syscalls/syscalls.c.obj
.PHONY : syscalls/syscalls.obj

# target to build an object file
syscalls/syscalls.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/syscalls/syscalls.c.obj
.PHONY : syscalls/syscalls.c.obj

syscalls/syscalls.i: syscalls/syscalls.c.i
.PHONY : syscalls/syscalls.i

# target to preprocess a source file
syscalls/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/syscalls/syscalls.c.i
.PHONY : syscalls/syscalls.c.i

syscalls/syscalls.s: syscalls/syscalls.c.s
.PHONY : syscalls/syscalls.s

# target to generate assembly for a file
syscalls/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stm32_timer_blink.elf.dir/build.make CMakeFiles/stm32_timer_blink.elf.dir/syscalls/syscalls.c.s
.PHONY : syscalls/syscalls.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bin"
	@echo "... flash"
	@echo "... hex"
	@echo "... size"
	@echo "... stm32_timer_blink.elf"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stm32/startup/startup_stm32f10x_md.obj"
	@echo "... stm32/startup/startup_stm32f10x_md.i"
	@echo "... stm32/startup/startup_stm32f10x_md.s"
	@echo "... stm32/system_stm32f10x.obj"
	@echo "... stm32/system_stm32f10x.i"
	@echo "... stm32/system_stm32f10x.s"
	@echo "... syscalls/syscalls.obj"
	@echo "... syscalls/syscalls.i"
	@echo "... syscalls/syscalls.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

